name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > release-sha256.txt
      - name: Test
        run: cat release-sha256.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-sha256.txt
          prerelease: ${{ contains(github.ref, '-beta.') }}

